apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask
        image: asia-east1-docker.pkg.dev/itp4122project/itp4122-repo/flask-app:latest
        ports:
        - containerPort: 8080
        command: ["gunicorn"]
        args: ["--bind", "0.0.0.0:8080", "microblog:app"]
        env:
        - name: DB_USER
          value: "esther"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
        - name: DB_HOST
          value: "35.201.179.178"
        - name: DB_NAME
          value: "eadb"
        - name: GCS_BUCKET_NAME
          value: "itp4122-upload-1780634365"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: SECRET_KEY
        - name: PUBLIC_BASE_URL
          value: "http://35.234.15.92"